#! /usr/bin/env bash

echo "== delete bucket"

#Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api list-objects-v2 \
--bucket $1 \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' |

aws s3api delete-objects \
--bucket $1 \
--delete file:///dev/stdin