#! /usr/bin/env bash

echo "== put random objects to a bucket"

# Exist if any error occurs
set -e

#Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

#Check for bucket name
if [ -z "$2" ]; then
    echo "The file path required to be uploaded is missing, give the path next to bucket"
    exit 1
fi


aws s3api put-object \
--bucket $1 \
--body $2 \
--key $(basename "$2")
